package io.newm.txbuilder.ktx

import com.google.iot.cbor.CborArray
import com.google.iot.cbor.CborInteger
import com.google.iot.cbor.CborMap
import com.google.iot.cbor.CborObject
import io.newm.kogmios.protocols.model.PlutusV2

/**
 * Convert Kogmios object into a cbor object that can be used as part of the scriptDataHash calculation.
 */
fun PlutusV2.toCborObject(): CborObject {
    return CborMap.create(
        mapOf(
            LANGUAGE_KEY_PLUTUSV2 to CborArray.create(
                listOf(
                    CborInteger.create(addIntegerCpuArgumentsIntercept), // "addInteger-cpu-arguments-intercept": 205665,
                    CborInteger.create(addIntegerCpuArgumentsSlope), // "addInteger-cpu-arguments-slope": 812,
                    CborInteger.create(addIntegerMemoryArgumentsIntercept), // "addInteger-memory-arguments-intercept": 1,
                    CborInteger.create(addIntegerMemoryArgumentsSlope), // "addInteger-memory-arguments-slope": 1,
                    CborInteger.create(appendByteStringCpuArgumentsIntercept), // "appendByteString-cpu-arguments-intercept": 1000,
                    CborInteger.create(appendByteStringCpuArgumentsSlope), // "appendByteString-cpu-arguments-slope": 571,
                    CborInteger.create(appendByteStringMemoryArgumentsIntercept), // "appendByteString-memory-arguments-intercept": 0,
                    CborInteger.create(appendByteStringMemoryArgumentsSlope), // "appendByteString-memory-arguments-slope": 1,
                    CborInteger.create(appendStringCpuArgumentsIntercept), // "appendString-cpu-arguments-intercept": 1000,
                    CborInteger.create(appendStringCpuArgumentsSlope), // "appendString-cpu-arguments-slope": 24177,
                    CborInteger.create(appendStringMemoryArgumentsIntercept), // "appendString-memory-arguments-intercept": 4,
                    CborInteger.create(appendStringMemoryArgumentsSlope), // "appendString-memory-arguments-slope": 1,
                    CborInteger.create(bDataCpuArguments), // "bData-cpu-arguments": 1000,
                    CborInteger.create(bDataMemoryArguments), // "bData-memory-arguments": 32,
                    CborInteger.create(blake2b256CpuArgumentsIntercept), // "blake2b_256-cpu-arguments-intercept": 117366,
                    CborInteger.create(blake2b256CpuArgumentsSlope), // "blake2b_256-cpu-arguments-slope": 10475,
                    CborInteger.create(blake2b256MemoryArguments), // "blake2b_256-memory-arguments": 4,
                    CborInteger.create(cekApplyCostExBudgetCPU), // "cekApplyCost-exBudgetCPU": 23000,
                    CborInteger.create(cekApplyCostExBudgetMemory), // "cekApplyCost-exBudgetMemory": 100,
                    CborInteger.create(cekBuiltinCostExBudgetCPU), // "cekBuiltinCost-exBudgetCPU": 23000,
                    CborInteger.create(cekBuiltinCostExBudgetMemory), // "cekBuiltinCost-exBudgetMemory": 100,
                    CborInteger.create(cekConstCostExBudgetCPU), // "cekConstCost-exBudgetCPU": 23000,
                    CborInteger.create(cekConstCostExBudgetMemory), // "cekConstCost-exBudgetMemory": 100,
                    CborInteger.create(cekDelayCostExBudgetCPU), // "cekDelayCost-exBudgetCPU": 23000,
                    CborInteger.create(cekDelayCostExBudgetMemory), // "cekDelayCost-exBudgetMemory": 100,
                    CborInteger.create(cekForceCostExBudgetCPU), // "cekForceCost-exBudgetCPU": 23000,
                    CborInteger.create(cekForceCostExBudgetMemory), // "cekForceCost-exBudgetMemory": 100,
                    CborInteger.create(cekLamCostExBudgetCPU), // "cekLamCost-exBudgetCPU": 23000,
                    CborInteger.create(cekLamCostExBudgetMemory), // "cekLamCost-exBudgetMemory": 100,
                    CborInteger.create(cekStartupCostExBudgetCPU), // "cekStartupCost-exBudgetCPU": 100,
                    CborInteger.create(cekStartupCostExBudgetMemory), // "cekStartupCost-exBudgetMemory": 100,
                    CborInteger.create(cekVarCostExBudgetCPU), // "cekVarCost-exBudgetCPU": 23000,
                    CborInteger.create(cekVarCostExBudgetMemory), // "cekVarCost-exBudgetMemory": 100,
                    CborInteger.create(chooseDataCpuArguments), // "chooseData-cpu-arguments": 19537,
                    CborInteger.create(chooseDataMemoryArguments), // "chooseData-memory-arguments": 32,
                    CborInteger.create(chooseListCpuArguments), // "chooseList-cpu-arguments": 175354,
                    CborInteger.create(chooseListMemoryArguments), // "chooseList-memory-arguments": 32,
                    CborInteger.create(chooseUnitCpuArguments), // "chooseUnit-cpu-arguments": 46417,
                    CborInteger.create(chooseUnitMemoryArguments), // "chooseUnit-memory-arguments": 4,
                    CborInteger.create(consByteStringCpuArgumentsIntercept), // "consByteString-cpu-arguments-intercept": 221973,
                    CborInteger.create(consByteStringCpuArgumentsSlope), // "consByteString-cpu-arguments-slope": 511,
                    CborInteger.create(consByteStringMemoryArgumentsIntercept), // "consByteString-memory-arguments-intercept": 0,
                    CborInteger.create(consByteStringMemoryArgumentsSlope), // "consByteString-memory-arguments-slope": 1,
                    CborInteger.create(constrDataCpuArguments), // "constrData-cpu-arguments": 89141,
                    CborInteger.create(constrDataMemoryArguments), // "constrData-memory-arguments": 32,
                    CborInteger.create(decodeUtf8CpuArgumentsIntercept), // "decodeUtf8-cpu-arguments-intercept": 497525,
                    CborInteger.create(decodeUtf8CpuArgumentsSlope), // "decodeUtf8-cpu-arguments-slope": 14068,
                    CborInteger.create(decodeUtf8MemoryArgumentsIntercept), // "decodeUtf8-memory-arguments-intercept": 4,
                    CborInteger.create(decodeUtf8MemoryArgumentsSlope), // "decodeUtf8-memory-arguments-slope": 2,
                    CborInteger.create(divideIntegerCpuArgumentsConstant), // "divideInteger-cpu-arguments-constant": 196500,
                    CborInteger.create(divideIntegerCpuArgumentsModelArgumentsIntercept), // "divideInteger-cpu-arguments-model-arguments-intercept": 453240,
                    CborInteger.create(divideIntegerCpuArgumentsModelArgumentsSlope), // "divideInteger-cpu-arguments-model-arguments-slope": 220,
                    CborInteger.create(divideIntegerMemoryArgumentsIntercept), // "divideInteger-memory-arguments-intercept": 0,
                    CborInteger.create(divideIntegerMemoryArgumentsMinimum), // "divideInteger-memory-arguments-minimum": 1,
                    CborInteger.create(divideIntegerMemoryArgumentsSlope), // "divideInteger-memory-arguments-slope": 1,
                    CborInteger.create(encodeUtf8CpuArgumentsIntercept), // "encodeUtf8-cpu-arguments-intercept": 1000,
                    CborInteger.create(encodeUtf8CpuArgumentsSlope), // "encodeUtf8-cpu-arguments-slope": 28662,
                    CborInteger.create(encodeUtf8MemoryArgumentsIntercept), // "encodeUtf8-memory-arguments-intercept": 4,
                    CborInteger.create(encodeUtf8MemoryArgumentsSlope), // "encodeUtf8-memory-arguments-slope": 2,
                    CborInteger.create(equalsByteStringCpuArgumentsConstant), // "equalsByteString-cpu-arguments-constant": 245000,
                    CborInteger.create(equalsByteStringCpuArgumentsIntercept), // "equalsByteString-cpu-arguments-intercept": 216773,
                    CborInteger.create(equalsByteStringCpuArgumentsSlope), // "equalsByteString-cpu-arguments-slope": 62,
                    CborInteger.create(equalsByteStringMemoryArguments), // "equalsByteString-memory-arguments": 1,
                    CborInteger.create(equalsDataCpuArgumentsIntercept), // "equalsData-cpu-arguments-intercept": 1060367,
                    CborInteger.create(equalsDataCpuArgumentsSlope), // "equalsData-cpu-arguments-slope": 12586,
                    CborInteger.create(equalsDataMemoryArguments), // "equalsData-memory-arguments": 1,
                    CborInteger.create(equalsIntegerCpuArgumentsIntercept), // "equalsInteger-cpu-arguments-intercept": 208512,
                    CborInteger.create(equalsIntegerCpuArgumentsSlope), // "equalsInteger-cpu-arguments-slope": 421,
                    CborInteger.create(equalsIntegerMemoryArguments), // "equalsInteger-memory-arguments": 1,
                    CborInteger.create(equalsStringCpuArgumentsConstant), // "equalsString-cpu-arguments-constant": 187000,
                    CborInteger.create(equalsStringCpuArgumentsIntercept), // "equalsString-cpu-arguments-intercept": 1000,
                    CborInteger.create(equalsStringCpuArgumentsSlope), // "equalsString-cpu-arguments-slope": 52998,
                    CborInteger.create(equalsStringMemoryArguments), // "equalsString-memory-arguments": 1,
                    CborInteger.create(fstPairCpuArguments), // "fstPair-cpu-arguments": 80436,
                    CborInteger.create(fstPairMemoryArguments), // "fstPair-memory-arguments": 32,
                    CborInteger.create(headListCpuArguments), // "headList-cpu-arguments": 43249,
                    CborInteger.create(headListMemoryArguments), // "headList-memory-arguments": 32,
                    CborInteger.create(iDataCpuArguments), // "iData-cpu-arguments": 1000,
                    CborInteger.create(iDataMemoryArguments), // "iData-memory-arguments": 32,
                    CborInteger.create(ifThenElseCpuArguments), // "ifThenElse-cpu-arguments": 80556,
                    CborInteger.create(ifThenElseMemoryArguments), // "ifThenElse-memory-arguments": 1,
                    CborInteger.create(indexByteStringCpuArguments), // "indexByteString-cpu-arguments": 57667,
                    CborInteger.create(indexByteStringMemoryArguments), // "indexByteString-memory-arguments": 4,
                    CborInteger.create(lengthOfByteStringCpuArguments), // "lengthOfByteString-cpu-arguments": 1000,
                    CborInteger.create(lengthOfByteStringMemoryArguments), // "lengthOfByteString-memory-arguments": 10,
                    CborInteger.create(lessThanByteStringCpuArgumentsIntercept), // "lessThanByteString-cpu-arguments-intercept": 197145,
                    CborInteger.create(lessThanByteStringCpuArgumentsSlope), // "lessThanByteString-cpu-arguments-slope": 156,
                    CborInteger.create(lessThanByteStringMemoryArguments), // "lessThanByteString-memory-arguments": 1,
                    CborInteger.create(lessThanEqualsByteStringCpuArgumentsIntercept), // "lessThanEqualsByteString-cpu-arguments-intercept": 197145,
                    CborInteger.create(lessThanEqualsByteStringCpuArgumentsSlope), // "lessThanEqualsByteString-cpu-arguments-slope": 156,
                    CborInteger.create(lessThanEqualsByteStringMemoryArguments), // "lessThanEqualsByteString-memory-arguments": 1,
                    CborInteger.create(lessThanEqualsIntegerCpuArgumentsIntercept), // "lessThanEqualsInteger-cpu-arguments-intercept": 204924,
                    CborInteger.create(lessThanEqualsIntegerCpuArgumentsSlope), // "lessThanEqualsInteger-cpu-arguments-slope": 473,
                    CborInteger.create(lessThanEqualsIntegerMemoryArguments), // "lessThanEqualsInteger-memory-arguments": 1,
                    CborInteger.create(lessThanIntegerCpuArgumentsIntercept), // "lessThanInteger-cpu-arguments-intercept": 208896,
                    CborInteger.create(lessThanIntegerCpuArgumentsSlope), // "lessThanInteger-cpu-arguments-slope": 511,
                    CborInteger.create(lessThanIntegerMemoryArguments), // "lessThanInteger-memory-arguments": 1,
                    CborInteger.create(listDataCpuArguments), // "listData-cpu-arguments": 52467,
                    CborInteger.create(listDataMemoryArguments), // "listData-memory-arguments": 32,
                    CborInteger.create(mapDataCpuArguments), // "mapData-cpu-arguments": 64832,
                    CborInteger.create(mapDataMemoryArguments), // "mapData-memory-arguments": 32,
                    CborInteger.create(mkConsCpuArguments), // "mkCons-cpu-arguments": 65493,
                    CborInteger.create(mkConsMemoryArguments), // "mkCons-memory-arguments": 32,
                    CborInteger.create(mkNilDataCpuArguments), // "mkNilData-cpu-arguments": 22558,
                    CborInteger.create(mkNilDataMemoryArguments), // "mkNilData-memory-arguments": 32,
                    CborInteger.create(mkNilPairDataCpuArguments), // "mkNilPairData-cpu-arguments": 16563,
                    CborInteger.create(mkNilPairDataMemoryArguments), // "mkNilPairData-memory-arguments": 32,
                    CborInteger.create(mkPairDataCpuArguments), // "mkPairData-cpu-arguments": 76511,
                    CborInteger.create(mkPairDataMemoryArguments), // "mkPairData-memory-arguments": 32,
                    CborInteger.create(modIntegerCpuArgumentsConstant), // "modInteger-cpu-arguments-constant": 196500,
                    CborInteger.create(modIntegerCpuArgumentsModelArgumentsIntercept), // "modInteger-cpu-arguments-model-arguments-intercept": 453240,
                    CborInteger.create(modIntegerCpuArgumentsModelArgumentsSlope), // "modInteger-cpu-arguments-model-arguments-slope": 220,
                    CborInteger.create(modIntegerMemoryArgumentsIntercept), // "modInteger-memory-arguments-intercept": 0,
                    CborInteger.create(modIntegerMemoryArgumentsMinimum), // "modInteger-memory-arguments-minimum": 1,
                    CborInteger.create(modIntegerMemoryArgumentsSlope), // "modInteger-memory-arguments-slope": 1,
                    CborInteger.create(multiplyIntegerCpuArgumentsIntercept), // "multiplyInteger-cpu-arguments-intercept": 69522,
                    CborInteger.create(multiplyIntegerCpuArgumentsSlope), // "multiplyInteger-cpu-arguments-slope": 11687,
                    CborInteger.create(multiplyIntegerMemoryArgumentsIntercept), // "multiplyInteger-memory-arguments-intercept": 0,
                    CborInteger.create(multiplyIntegerMemoryArgumentsSlope), // "multiplyInteger-memory-arguments-slope": 1,
                    CborInteger.create(nullListCpuArguments), // "nullList-cpu-arguments": 60091,
                    CborInteger.create(nullListMemoryArguments), // "nullList-memory-arguments": 32,
                    CborInteger.create(quotientIntegerCpuArgumentsConstant), // "quotientInteger-cpu-arguments-constant": 196500,
                    CborInteger.create(quotientIntegerCpuArgumentsModelArgumentsIntercept), // "quotientInteger-cpu-arguments-model-arguments-intercept": 453240,
                    CborInteger.create(quotientIntegerCpuArgumentsModelArgumentsSlope), // "quotientInteger-cpu-arguments-model-arguments-slope": 220,
                    CborInteger.create(quotientIntegerMemoryArgumentsIntercept), // "quotientInteger-memory-arguments-intercept": 0,
                    CborInteger.create(quotientIntegerMemoryArgumentsMinimum), // "quotientInteger-memory-arguments-minimum": 1,
                    CborInteger.create(quotientIntegerMemoryArgumentsSlope), // "quotientInteger-memory-arguments-slope": 1,
                    CborInteger.create(remainderIntegerCpuArgumentsConstant), // "remainderInteger-cpu-arguments-constant": 196500,
                    CborInteger.create(remainderIntegerCpuArgumentsModelArgumentsIntercept), // "remainderInteger-cpu-arguments-model-arguments-intercept": 453240,
                    CborInteger.create(remainderIntegerCpuArgumentsModelArgumentsSlope), // "remainderInteger-cpu-arguments-model-arguments-slope": 220,
                    CborInteger.create(remainderIntegerMemoryArgumentsIntercept), // "remainderInteger-memory-arguments-intercept": 0,
                    CborInteger.create(remainderIntegerMemoryArgumentsMinimum), // "remainderInteger-memory-arguments-minimum": 1,
                    CborInteger.create(remainderIntegerMemoryArgumentsSlope), // "remainderInteger-memory-arguments-slope": 1,
                    CborInteger.create(serialiseDataCpuArgumentsIntercept), // "serialiseData-cpu-arguments-intercept": 1159724,
                    CborInteger.create(serialiseDataCpuArgumentsSlope), // "serialiseData-cpu-arguments-slope": 392670,
                    CborInteger.create(serialiseDataMemoryArgumentsIntercept), // "serialiseData-memory-arguments-intercept": 0,
                    CborInteger.create(serialiseDataMemoryArgumentsSlope), // "serialiseData-memory-arguments-slope": 2,
                    CborInteger.create(sha2256CpuArgumentsIntercept), // "sha2_256-cpu-arguments-intercept": 806990,
                    CborInteger.create(sha2256CpuArgumentsSlope), // "sha2_256-cpu-arguments-slope": 30482,
                    CborInteger.create(sha2256MemoryArguments), // "sha2_256-memory-arguments": 4,
                    CborInteger.create(sha3256CpuArgumentsIntercept), // "sha3_256-cpu-arguments-intercept": 1927926,
                    CborInteger.create(sha3256CpuArgumentsSlope), // "sha3_256-cpu-arguments-slope": 82523,
                    CborInteger.create(sha3256MemoryArguments), // "sha3_256-memory-arguments": 4,
                    CborInteger.create(sliceByteStringCpuArgumentsIntercept), // "sliceByteString-cpu-arguments-intercept": 265318,
                    CborInteger.create(sliceByteStringCpuArgumentsSlope), // "sliceByteString-cpu-arguments-slope": 0,
                    CborInteger.create(sliceByteStringMemoryArgumentsIntercept), // "sliceByteString-memory-arguments-intercept": 4,
                    CborInteger.create(sliceByteStringMemoryArgumentsSlope), // "sliceByteString-memory-arguments-slope": 0,
                    CborInteger.create(sndPairCpuArguments), // "sndPair-cpu-arguments": 85931,
                    CborInteger.create(sndPairMemoryArguments), // "sndPair-memory-arguments": 32,
                    CborInteger.create(subtractIntegerCpuArgumentsIntercept), // "subtractInteger-cpu-arguments-intercept": 205665,
                    CborInteger.create(subtractIntegerCpuArgumentsSlope), // "subtractInteger-cpu-arguments-slope": 812,
                    CborInteger.create(subtractIntegerMemoryArgumentsIntercept), // "subtractInteger-memory-arguments-intercept": 1,
                    CborInteger.create(subtractIntegerMemoryArgumentsSlope), // "subtractInteger-memory-arguments-slope": 1,
                    CborInteger.create(tailListCpuArguments), // "tailList-cpu-arguments": 41182,
                    CborInteger.create(tailListMemoryArguments), // "tailList-memory-arguments": 32,
                    CborInteger.create(traceCpuArguments), // "trace-cpu-arguments": 212342,
                    CborInteger.create(traceMemoryArguments), // "trace-memory-arguments": 32,
                    CborInteger.create(unBDataCpuArguments), // "unBData-cpu-arguments": 31220,
                    CborInteger.create(unBDataMemoryArguments), // "unBData-memory-arguments": 32,
                    CborInteger.create(unConstrDataCpuArguments), // "unConstrData-cpu-arguments": 32696,
                    CborInteger.create(unConstrDataMemoryArguments), // "unConstrData-memory-arguments": 32,
                    CborInteger.create(unIDataCpuArguments), // "unIData-cpu-arguments": 43357,
                    CborInteger.create(unIDataMemoryArguments), // "unIData-memory-arguments": 32,
                    CborInteger.create(unListDataCpuArguments), // "unListData-cpu-arguments": 32247,
                    CborInteger.create(unListDataMemoryArguments), // "unListData-memory-arguments": 32,
                    CborInteger.create(unMapDataCpuArguments), // "unMapData-cpu-arguments": 38314,
                    CborInteger.create(unMapDataMemoryArguments), // "unMapData-memory-arguments": 32,
                    CborInteger.create(verifyEcdsaSecp256k1SignatureCpuArguments), // "verifyEcdsaSecp256k1Signature-cpu-arguments": 35892428,
                    CborInteger.create(verifyEcdsaSecp256k1SignatureMemoryArguments), // "verifyEcdsaSecp256k1Signature-memory-arguments": 10,
                    CborInteger.create(verifyEd25519SignatureCpuArgumentsIntercept), // "verifyEd25519Signature-cpu-arguments-intercept": 57996947,
                    CborInteger.create(verifyEd25519SignatureCpuArgumentsSlope), // "verifyEd25519Signature-cpu-arguments-slope": 18975,
                    CborInteger.create(verifyEd25519SignatureMemoryArguments), // "verifyEd25519Signature-memory-arguments": 10,
                    CborInteger.create(verifySchnorrSecp256k1SignatureCpuArgumentsIntercept), // "verifySchnorrSecp256k1Signature-cpu-arguments-intercept": 38887044,
                    CborInteger.create(verifySchnorrSecp256k1SignatureCpuArgumentsSlope), // "verifySchnorrSecp256k1Signature-cpu-arguments-slope": 32947,
                    CborInteger.create(verifySchnorrSecp256k1SignatureMemoryArguments), // "verifySchnorrSecp256k1Signature-memory-arguments": 10
                )
            )
        )
    )
}

// PlutusV1 == 0, PlutusV2 == 1
private val LANGUAGE_KEY_PLUTUSV2 by lazy { CborInteger.create(1) }
