package io.newm.server.features.user

import io.newm.server.features.user.model.User
import io.newm.server.model.ClientPlatform
import io.newm.shared.auth.Password

val testUser1 = User(
    signupPlatform = ClientPlatform.Studio,
    firstName = "FirstName1",
    lastName = "LastName1",
    nickname = "Nickname1",
    pictureUrl = "https://projectnewm.io/pic1.jpg",
    bannerUrl = "https://projectnewm.io/banner1.jpg",
    websiteUrl = "https://user1.com",
    twitterUrl = "https://twitter.com/user1",
    instagramUrl = "https://instagram.com/user1",
    spotifyProfile = "https://open.spotify.com/artist/SpotifyProfile1",
    soundCloudProfile = "https://soundcloud.com/SoundCloudProfile1",
    appleMusicProfile = "https://music.apple.com/us/artist/AppleMusicProfile1/12345678",
    location = "Location1",
    role = "Role1",
    genre = "Genre1",
    biography = "Biography1",
    walletAddress = "addr1111111111111111111111111111",
    email = "testuser1@projectnewm.io",
    newPassword = Password("Password1"),
    confirmPassword = Password("Password1"),
    currentPassword = Password("Password2"),
    authCode = "123456",
    isni = "isni1",
    ipi = "ipi1",
    companyName = "Company1",
    companyLogoUrl = "https://projectnewm.io/logo1.jpg",
    companyIpRights = true,
    dspPlanSubscribed = false,
)

val testUser2 = User(
    signupPlatform = ClientPlatform.Android,
    firstName = "FirstName2",
    lastName = "LastName2",
    nickname = "Nickname2",
    pictureUrl = "https://projectnewm.io/pic2.jpg",
    bannerUrl = "https://projectnewm.io/banner2.jpg",
    websiteUrl = "https://user2.com",
    twitterUrl = "https://twitter.com/user2",
    instagramUrl = "https://instagram.com/user2",
    spotifyProfile = "https://open.spotify.com/artist/SpotifyProfile2",
    soundCloudProfile = "https://soundcloud.com/SoundCloudProfile2",
    appleMusicProfile = "https://music.apple.com/us/artist/AppleMusicProfile2/123456789",
    location = "Location2",
    role = "Role2",
    genre = "Genre2",
    biography = "Biography2",
    walletAddress = "addr2222222222222222222222222222",
    email = "testuser2@projectnewm.io",
    newPassword = Password("Password2"),
    confirmPassword = Password("Password2"),
    currentPassword = Password("Password1"),
    authCode = "123456",
    isni = "isni2",
    ipi = "ipi2",
    companyName = "Company2",
    companyLogoUrl = "https://projectnewm.io/logo2.jpg",
    companyIpRights = false,
    dspPlanSubscribed = true,
)
