#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER ${DATABASE_USERNAME};
  CREATE DATABASE ${DATABASE_NAME};
  ALTER USER ${DATABASE_USERNAME} WITH PASSWORD '${DATABASE_PASSWORD}';
  ALTER USER ${DATABASE_USERNAME} VALID UNTIL 'infinity';
  ALTER DATABASE ${DATABASE_NAME} OWNER TO ${DATABASE_USERNAME};
EOSQL

