package io.newm.chain.database.entity

data class ChainBlock(
    val id: Long? = null,
    val blockNumber: Long,
    val slotNumber: Long,
    val hash: String,
    val prevHash: String,
    val nodeVkey: String,
    val nodeVrfVkey: String,
    val blockVrf: String,
    val blockVrfProof: String,
    val etaVrf0: String,
    val etaVrf1: String,
    val leaderVrf0: String,
    val leaderVrf1: String,
    val blockSize: Int,
    val blockBodyHash: String,
    val poolOpcert: String,
    val sequenceNumber: Int,
    val kesPeriod: Int,
    val sigmaSignature: String,
    val protocolMajorVersion: Int,
    val protocolMinorVersion: Int,
    val transactionDestAddresses: Set<String>,
    val stakeDestAddresses: Set<PaymentStakeAddress>,
//    val isTip: Boolean,
//    val created: Long,
//    val transactionIdsInBlock: List<String>,
)
